version: '3'

services:
  server:
    build: ./api
    restart: unless-stopped
    environment:
      MONGODB_DATABASE: db
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: pass
      MONGODB_HOSTNAME: mongodb
    ports:
      - 5000:5000
    volumes:
      - .:/srv/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
