version: '3'

services:
  server:
    build: ./api
    restart: unless-stopped
    environment:
      FLASK_ENV:
      APP_ENV: "development"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: db
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: pass
      MONGODB_HOSTNAME: mongodb
    volumes:
      - .:/srv/app
    ports:
      - 8000:5000
    networks:
      - frontend
      - backend
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: db
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend
