version: '3'

services:
  server:
    build: ./api
    restart: unless-stopped
    environment:
      FLASK_ENV:
      APP_ENV: "development"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: db
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: pass
      MONGODB_HOSTNAME: mongodb
    volumes:
      - .:/srv/app
    ports:
      - 8000:5000
